Add option for skipping Git working tree check
strapi/codemods pull request #38
Opened 2022-08-20 12:33 UTC by dennisameling

Fixes #37. Happy to take a different approach if the team prefers that. This at least unblocked my workflow!

2022-08-23 08:41 UTC, markkaylor commented
Hi @dennisameling thank you for the pull request, I will try to review it before the end of the week.

2022-08-31 11:05 UTC, markkaylor requested changes

2022-08-31 11:05 UTC, markkaylor commented on bin/commands/migrate.js
> +const migrate = async (type, path, pathForV4Plugin, cliOptions) => {
I think we should change this to accept an object `{type, path, pathForV4Plugin, cliOptions}`

2022-08-31 11:05 UTC, markkaylor commented on bin/cli.js
> +    await migrate('application', path, undefined, options);
See my other comment, then here: `{type: 'application', path, cliOptions: options}`

2022-08-31 11:06 UTC, markkaylor commented on bin/cli.js
> +    await migrate('application', path, undefined, options);
and you will have to make the update anywhere else `migrate` is called

2022-10-27 16:57 UTC, derrickmehaffy commented
Since there has been no update to this PR I'm going to mark it as closed.

2022-10-27 16:57 UTC, closed without merging