fix(formatting): fix remove code formatting - fixes: #40
strapi/codemods pull request #41
Opened 2022-09-02 05:55 UTC by emahuni

See issue #40 for more details...

2022-09-02 17:38 UTC, derrickmehaffy requested changes

2022-09-02 17:38 UTC, derrickmehaffy commented on .prettierrc.js
>  module.exports = {
Can we keep this file please as it's for this repo, not projects being migrated.

2022-09-02 17:38 UTC, derrickmehaffy commented on package.json
> -    "prettier": "^2.4.1"
Same here can we keep prettier for this repo

2022-09-14 14:53 UTC, markkaylor commented on .prettierrc.js
> +  printWidth: 120,
Please don't change these values they are set to match the config we use in the Strapi core repo

2022-10-27 16:57 UTC, derrickmehaffy commented
Since there has been no update to this PR I'm going to mark it as closed.

2022-10-27 16:57 UTC, closed without merging